In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
medical_df=pd.read_csv('medical.csv')

In [3]:
medical_df.head(10)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
5   31  female  25.740         0     no  southeast   3756.62160
6   46  female  33.440         1     no  southeast   8240.58960
7   37  female  27.740         3     no  northwest   7281.50560
8   37    male  29.830         2     no  northeast   6406.41070
9   60  female  25.840         0     no  northwest  28923.13692


### One-hot Encoding

The "region" column contains 4 values, so we'll need to use hot encoding and create a new column for each region.

In [4]:
from sklearn import preprocessing
enc=preprocessing.OneHotEncoder(handle_unknown='ignore')
enc.fit(medical_df[['region']])
one_hot=enc.transform(medical_df[['region']]).toarray()

OneHotEncoder()

If you encounter error like it is not in pandas framework then, use the below code(The below code is just an example, not a part of this Dataset

In [ ]:
from sklearn.compose import ColumnTransformer

encoder=OneHotEncoder(handle_unknown='ignore')
columntrans=ColumnTransformer([("cat",encoder,categorical_cols)], remainder="passthrough")

In [5]:
enc.categories_

[array(['northeast', 'northwest', 'southeast', 'southwest'], dtype=object)]

In [7]:
one_hot

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       ...,
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.]])

In [8]:
# Inserting One Hot Encoded columns into the dataset
medical_df[['northeast','northwest','southeast','southwest']]=one_hot

In [9]:
medical_df.head(10)

,age,sex,bmi,children,smoker,region,charges,northeast,northwest,southeast,southwest
0,19,female,27.900,0,yes,southwest,16884.92400,0.0,0.0,0.0,1.0
1,18,male,33.770,1,no,southeast,1725.55230,0.0,0.0,1.0,0.0
2,28,male,33.000,3,no,southeast,4449.46200,0.0,0.0,1.0,0.0
3,33,male,22.705,0,no,northwest,21984.47061,0.0,1.0,0.0,0.0
4,32,male,28.880,0,no,northwest,3866.85520,0.0,1.0,0.0,0.0
5,31,female,25.740,0,no,southeast,3756.62160,0.0,0.0,1.0,0.0
6,46,female,33.440,1,no,southeast,8240.58960,0.0,0.0,1.0,0.0
7,37,female,27.740,3,no,northwest,7281.50560,0.0,1.0,0.0,0.0
8,37,male,29.830,2,no,northeast,6406.41070,1.0,0.0,0.0,0.0
9,60,female,25.840,0,no,northwest,28923.13692,0.0,1.0,0.0,0.0

### StandardScaler

In [10]:
from sklearn.preprocessing import StandardScaler

numeric_cols=['age','bmi','children']
scaler=StandardScaler()
scaler.fit(medical_df[numeric_cols])
scaled_input=scaler.transform(medical_df[numeric_cols])

StandardScaler()

In [12]:
scaled_input

array([[-1.43876426, -0.45332   , -0.90861367],
       [-1.50996545,  0.5096211 , -0.07876719],
       [-0.79795355,  0.38330685,  1.58092576],
       ...,
       [-1.50996545,  1.0148781 , -0.90861367],
       [-1.29636188, -0.79781341, -0.90861367],
       [ 1.55168573, -0.26138796, -0.90861367]])

In [13]:
scaler.mean_

array([39.20702541, 30.66339686,  1.09491779])

In [14]:
scaler.var_

array([197.25385199,  37.16008997,   1.45212664])

### MinMaxScaler

In [16]:
from sklearn.preprocessing import MinMaxScaler

numeric_cols=['age','bmi','children']
scaler=MinMaxScaler()
scaler.fit(medical_df[numeric_cols])
scaled_input=scaler.transform(medical_df[numeric_cols])

In [17]:
scaled_input

array([[0.02173913, 0.3212268 , 0.        ],
       [0.        , 0.47914985, 0.2       ],
       [0.2173913 , 0.45843422, 0.6       ],
       ...,
       [0.        , 0.56201238, 0.        ],
       [0.06521739, 0.26472962, 0.        ],
       [0.93478261, 0.35270379, 0.        ]])